name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package javafx:jlink --file pom.xml
    - uses: rlespinasse/github-slug-action@master
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: openpnp-v3-${{ env.GITHUB_REF_SLUG }}-${{ runner.os }}
        path: target/image
